Repository prgrms-web-devcourse/FEDC5_I_REACT_DeepDive, pull requests merged in 2024-02, with the labels that each got.

#9 2-4 렌더링은 어떻게 일어나는가?, 2-5 컴포넌트와 함수의 무거운 연산을 기억해 두는 메모이제이션
  Chapter_2/GeonHo/4. 렌더링은 어떻게 일어나는가?/정리.md
  Chapter_2/GeonHo/5. 컴포넌트와 함수의 무거운 연산을 기억해 두는 메모이제이션/정리.md
Labels: 프론트, 알게된 내용, 모던 리액트 딥 다이브, 스터디

#4 2.3 클래스형 컴포넌트와 함수형 컴포넌트
  Chapter_2/mino/2-3/2.3 클래스형 컴포넌트와 함수형 컴포넌트.md
Labels: 프론트, 알게된 내용, 모던 리액트 딥 다이브, 스터디

#13 [DOCS] 3-1 useEffect
  Chapter_3/지인혁/1. 리액트의 모든 훅 파헤치기/README.md
Labels: 모던 리액트 딥 다이브

#10 2-4 렌더링은 어떻게 일어나는가?, 2-5 컴포넌트와 함수의 무거운 연산을 기억해 두는 메모이제이션
  Chapter_2/백준원/2-4.md
  Chapter_2/백준원/2-5.md
  Chapter_3/백준원/3-1.md
Labels: 프론트, 알게된 내용, 모던 리액트 딥 다이브
